### ISSUE TITLE
update classifiers

### ISSUE THREAD

**Issue by anukaal** [linkedin/FastTreeSHAP#1]
use python new versions 3.7, 3.8, 3.9 and 3.10

**Comment by jlyang1990** [comment]
Hi @anukaal , could you explain more on this issue? We actually tested this package on multiple Python new versions (higher than 3.6), and we found this package worked well. Thanks!

**Comment by jlyang1990** [comment]
Added Python new versions 3.7, 3.8, 3.9 and 3.10 into setup.py.
