### ISSUE TITLE
NumbaDeprecationWarning 

### ISSUE THREAD

**Issue by julnow** [linkedin/FastTreeSHAP#23]
Just faced the same problem as the original SHAP package:
https://github.com/slundberg/shap/issues/2909

**Comment by jlyang1990** [comment]
Let's see how the PR https://github.com/dsgibbons/shap/pull/9 gets merged into `shap` package. If that merge is successful, we should do the same in this package.

**Comment by jlyang1990** [comment]
Addressed in the PR https://github.com/linkedin/FastTreeSHAP/pull/27.

**Comment by julnow** [comment]
Hi @jlyang1990, is the new release planned anytime soon?

**Comment by jlyang1990** [comment]
@julnow New release added https://pypi.org/project/fasttreeshap/0.1.5/.

**Comment by julnow** [comment]
Great, thanks! 🎉
