### ISSUE TITLE
pip install fasttreeshap fails

### ISSUE THREAD

**Issue by unnikrishnansivakumar** [linkedin/FastTreeSHAP#9]
Fails while trying to build the wheel.

I am using Python 3.7

**Comment by unnikrishnansivakumar** [comment]
I think the failure was due to not having the latest version of the MSVC build tools. It worked after installing the VC++ build tool.

**Comment by noahaus** [comment]
This is an old comment but want to confirm that if you have issues downloading FastTreeSHAP on Visual Studio, what the commenter stated is the correct way forward
